name: FossLight

on:
  push:
    branches:
      - main

jobs:
  fosslight:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install FossLight
        run: |
          pip install fosslight_source

      - name: Run FossLight
        run: fosslight_source -p ./ -f yaml -j

      - name: Upload FossLight Report
        uses: actions/upload-artifact@v2
        with:
          name: fosslight-report
          path: fosslight-report.json
