name: ORT sample

on:
  push:
    branches: [main]

jobs:
  ort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run GitHub Action for ORT
        id: ort_scan
        uses: oss-review-toolkit/ort-ci-github-action@b6d71a83acba8619f16b30c008f212a7a572f8e8 #v1
        with:
          allow-dynamic-versions: 'true'
          fail-on: 'violations'
          run: >
            cache-dependencies,
            metadata-labels,
            analyzer,
            reporter,
            upload-results
